services:
  monitoring:
    container_name: sentinel-monitoring
    build:
      context: .
      dockerfile: SentinelApi.Monitoring/SentinelApi.Monitoring/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Monitoring=Server=sql-server;Database=SentinelMonitoring;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - SentinelMonitoring__ApiKey=${SENTINEL_MONITORING_API_KEY}
      - Smtp__Host=smtp4dev
      - Smtp__Port=25
      - Smtp__UserName=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD}
      - Smtp__Email=sentinel@local.test
    depends_on:
      - sql-server
      - smtp4dev

  identity:
    container_name: sentinel-identity
    build:
      context: .
      dockerfile: SentinelApi.Identity/SentinelApi.Identity/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Identity=Server=sql-server;Database=SentinelIdentity;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__PrivateKey=${JWT_PRIVATE_KEY}
      - Seed__AdminLogin=${SEED_ADMIN_LOGIN}
      - Seed__AdminEmail=${SEED_ADMIN_EMAIL}
      - Seed__AdminPassword=${SEED_ADMIN_PASSWORD}
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "14330:1433"
    volumes:
      - sql-server-data:/var/opt/mssql

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: sentinel-smtp4dev
    ports:
      - "5000:80"
      - "2525:25"

volumes:
  sql-server-data:
