<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>SentinelLib.Monitoring.SDK</PackageId>
        <Version>1.0.0</Version>
        <Authors>SergioKostyukov</Authors>
        <Description>ASP.NET Core monitoring integration library for Sentinel system</Description>
        <PackageTags>monitoring;health-check;sentinel</PackageTags>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <NoWarn>$(NoWarn);1573</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    </ItemGroup>

</Project>