<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="NLog.Web.AspNetCore" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SentinelApi.Monitoring.Domain\SentinelApi.Monitoring.Domain.csproj" />
        <ProjectReference Include="..\..\SentinelLib.Monitoring.SDK\SentinelLib.Monitoring.SDK\SentinelLib.Monitoring.SDK.csproj" />
        <ProjectReference Include="..\..\SentinelLib.Identity.Security\SentinelLib.Identity.Security\SentinelLib.Identity.Security.csproj" />
    </ItemGroup>

</Project>
